stages:
  - test

eslint:
  stage: test
  image: node:6
  cache:
    paths:
      - node_modules/
  script:
    - npm install --quiet eslint@$(node -p 'require("./package.json").devDependencies.eslint')
    - npm install --quiet babel-eslint@$(node -p 'require("./package.json").devDependencies["babel-eslint"]')
    - npm run -s eslint
  tags:
    - docker
